language: r
cache: packages
r: release

env:
  global:
  - RGL_USE_NULL=TRUE
  - _R_CHECK_DONTTEST_EXAMPLES_=FALSE

r_build_args: --no-build-vignettes
r_check_args: "--no-vignettes --as-cran --install-args=--build"

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgsl0-dev libegl1-mesa libegl1-mesa-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev python-pip libblas-dev libgit2-dev
  - pip install --user numpy
  - export RGL_USE_NULL=TRUE

r_packages:
  - covr
  - devtools
  - Rcpp
  - spam
  - RCurl
  - plotly
  - fields
  - bitops
  - ggpubr
  - ggsci
  - maps
  - memuse
  - dplyr
  - reshape2
  - ggplot2
  - MDSMap
  - smacof
  - princurve
  - dendextend
  - rstudioapi
  - scatterplot3d
  - crayon
  - cli
  - magrittr
  - vcfR
  - zoo
  - testthat
  - polymapR
  - updog

after_success:
  - Rscript -e 'library(covr); codecov()'
  
